import './sass/main.scss';
import './js/modal';
import './js/our-team-modal';
import './js/pagination';
import * as searchByKeyword from './js/search_by_keyword';
import './js/up-btn';
import './js/spinner';
import './js/search_trend_collection';
import './js/watched';
import './js/libraryBtns';
import "./js/markup-modal";
import './js/dark-light-theme';
import "./js/library-pagination";
